import type { AppLanguage } from '../i18n';

export const accountGateCopy={
 en:{back:'Back',title:'Your days. Your patterns.',intro:'Start on this device or use an account to sync your entries.',signed:'Signed in as',account:'Account',continue:'Continue',signout:'Sign out',device:'Start on this device',local:'No registration. Data stays local.',signin:'Sign in',existing:'Use an existing account.',create:'Create account',sync:'Sync across devices.',welcome:'Welcome back',email:'Email',password:'Password',wait:'One moment…',newAccount:'Create a new account',haveAccount:'Already have an account? Sign in',created:'Account created. Please confirm your email, then sign in.',failed:'Sign-in failed'},
 de:{back:'Zurück',title:'Deine Tage. Deine Muster.',intro:'Starte auf diesem Gerät oder nutze ein Konto, um deine Einträge zu synchronisieren.',signed:'Angemeldet als',account:'Konto',continue:'Weiter',signout:'Abmelden',device:'Auf diesem Gerät starten',local:'Keine Registrierung. Deine Daten bleiben lokal.',signin:'Anmelden',existing:'Ein bestehendes Konto verwenden.',create:'Konto erstellen',sync:'Zwischen Geräten synchronisieren.',welcome:'Willkommen zurück',email:'E-Mail',password:'Passwort',wait:'Einen Moment…',newAccount:'Neues Konto erstellen',haveAccount:'Du hast schon ein Konto? Anmelden',created:'Konto erstellt. Bitte bestätige deine E-Mail und melde dich danach an.',failed:'Anmeldung fehlgeschlagen'},
 fr:{back:'Retour',title:'Tes journées. Tes habitudes.',intro:'Commence sur cet appareil ou utilise un compte pour synchroniser tes entrées.',signed:'Connecté en tant que',account:'Compte',continue:'Continuer',signout:'Se déconnecter',device:'Commencer sur cet appareil',local:'Aucune inscription. Tes données restent sur cet appareil.',signin:'Se connecter',existing:'Utiliser un compte existant.',create:'Créer un compte',sync:'Synchroniser entre les appareils.',welcome:'Bon retour',email:'E-mail',password:'Mot de passe',wait:'Un instant…',newAccount:'Créer un nouveau compte',haveAccount:'Tu as déjà un compte ? Se connecter',created:'Compte créé. Confirme ton e-mail, puis connecte-toi.',failed:'Échec de la connexion'},
 ar:{back:'رجوع',title:'أيامك. أنماطك.',intro:'ابدأ على هذا الجهاز أو استخدم حساباً لمزامنة تسجيلاتك.',signed:'مسجل الدخول باسم',account:'الحساب',continue:'متابعة',signout:'تسجيل الخروج',device:'ابدأ على هذا الجهاز',local:'بدون تسجيل. تبقى البيانات محلياً.',signin:'تسجيل الدخول',existing:'استخدم حساباً موجوداً.',create:'إنشاء حساب',sync:'للمزامنة بين الأجهزة.',welcome:'مرحباً بعودتك',email:'البريد الإلكتروني',password:'كلمة المرور',wait:'لحظة…',newAccount:'إنشاء حساب جديد',haveAccount:'لديك حساب؟ سجّل الدخول',created:'تم إنشاء الحساب. أكّد بريدك الإلكتروني ثم سجّل الدخول.',failed:'تعذر تسجيل الدخول'}
} satisfies Record<AppLanguage,Record<string,string>>;

export const accountGateLanguageNames:Record<AppLanguage,string>={de:'Deutsch',en:'English',fr:'Français',ar:'العربية'};
