import React from 'react';
import { Search, Activity, Home, Plus } from 'lucide-react';
import { ActiveTab, FilterState } from '../types';

interface HeaderProps { activeTab: ActiveTab; setActiveTab: (tab: ActiveTab) => void; onOpenAddModal: () => void; onOpenCheckInModal: () => void; filterState: FilterState; setFilterState: React.Dispatch<React.SetStateAction<FilterState>>; isMobilePreviewMode: boolean; setIsMobilePreviewMode: (mode: boolean) => void; totalMoments: number; }
export const Header: React.FC<HeaderProps> = ({ activeTab,setActiveTab,onOpenAddModal,filterState,setFilterState }) => {
 const [search,setSearch]=React.useState(false);
 return <header className="sticky top-0 z-30 bg-[#F7F5F0]/92 backdrop-blur-xl border-b border-[#EAE5DC]/70"><div className="max-w-5xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between gap-4"><button onClick={()=>setActiveTab('today')} className="font-display font-black text-xl tracking-tight text-[#252824]">Rhythm</button><nav className="hidden md:flex items-center gap-1 bg-white rounded-full p-1 border border-[#E8E3DA]"><button onClick={()=>setActiveTab('today')} className={`rounded-full px-4 py-2 text-xs font-bold flex gap-1.5 items-center ${activeTab==='today'?'bg-[#252824] text-white':'text-[#706F68]'}`}><Home className="w-3.5 h-3.5"/>Heute</button><button onClick={onOpenAddModal} className="rounded-full px-4 py-2 text-xs font-bold flex gap-1.5 items-center text-[#9B4D32]"><Plus className="w-3.5 h-3.5"/>Hinzufügen</button><button onClick={()=>setActiveTab('type_analysis')} className={`rounded-full px-4 py-2 text-xs font-bold flex gap-1.5 items-center ${activeTab==='type_analysis'?'bg-[#252824] text-white':'text-[#706F68]'}`}><Activity className="w-3.5 h-3.5"/>Muster</button></nav><div className="relative">{search?<div className="flex items-center"><Search className="absolute left-3 w-4 h-4 text-[#99958C]"/><input value={filterState.searchQuery} onChange={e=>setFilterState(p=>({...p,searchQuery:e.target.value}))} autoFocus placeholder="Suchen" className="w-40 rounded-full bg-white border border-[#E8E3DA] py-2.5 pl-9 pr-7 text-xs outline-none"/><button onClick={()=>{setSearch(false);setFilterState(p=>({...p,searchQuery:''}))}} className="absolute right-2.5">×</button></div>:<button onClick={()=>setSearch(true)} className="w-10 h-10 rounded-full bg-white border border-[#E8E3DA] flex items-center justify-center text-[#77736B]" aria-label="Suchen"><Search className="w-4 h-4"/></button>}</div></div></header>;
};
