import React from 'react';
import { Activity, BookOpen, CalendarDays, Languages, Plus } from 'lucide-react';
import { ActiveTab } from '../types';
import { useLanguage, type AppLanguage } from '../i18n';
import { trackUx } from '../utils/uxAnalytics';
import { LanguagePicker } from './LanguagePicker';
interface MobileBottomNavProps { activeTab: ActiveTab; setActiveTab: (tab: ActiveTab) => void; onCapture: () => void; favoriteCount: number; }
const navCopy:Record<AppLanguage,{discoveries:string;moments:string;language:string}>={
  en:{discoveries:'Discoveries',moments:'My moments',language:'Language'},
  de:{discoveries:'Entdeckungen',moments:'Meine Momente',language:'Sprache'},
  fr:{discoveries:'Découvertes',moments:'Mes moments',language:'Langue'},
  ar:{discoveries:'اكتشافاتك',moments:'لحظاتي',language:'اللغة'},
};
export const MobileBottomNav: React.FC<MobileBottomNavProps> = ({ activeTab, setActiveTab, onCapture }) => { const {language,t}=useLanguage(); const [languageOpen,setLanguageOpen]=React.useState(false); const item='min-h-[58px] rounded-[18px] flex flex-col items-center justify-center gap-1 text-[9px] font-black'; const nav=(tab:ActiveTab,route:string)=>{trackUx({eventName:'nav_tapped',surface:'bottom_nav',language,metadata:{route}});setActiveTab(tab)}; const add=()=>{trackUx({eventName:'add_tapped',surface:'bottom_nav',language,metadata:{source:'bottom_nav'}});onCapture()}; const copy=navCopy[language]; return <><nav className="fixed bottom-0 left-0 right-0 z-40 px-3 pt-3 pb-[max(.65rem,env(safe-area-inset-bottom))] md:hidden bg-gradient-to-t from-[#F7F3EC] via-[#F7F3EC]/96 to-transparent" aria-label={t('mainNav')}><div className="max-w-md mx-auto grid grid-cols-5 items-end rounded-[28px] bg-[#FFFDF9] px-2 pt-2 pb-1.5 shadow-[0_10px_32px_rgba(48,38,28,.16)] border border-[#E8DED0]"><button type="button" onClick={()=>nav('type_analysis','discoveries')} className={`${item} ${activeTab==='type_analysis'?'text-[#506B48]':'text-[#858078]'}`}><Activity className="w-5 h-5"/><span>{copy.discoveries}</span></button><button type="button" onClick={()=>nav('today','moments')} className={`${item} text-[#858078]`}><BookOpen className="w-5 h-5"/><span>{copy.moments}</span></button><button type="button" onClick={add} className="relative -mt-6 mx-auto w-[64px] h-[64px] rounded-full bg-[#526B48] text-white flex items-center justify-center shadow-[0_14px_30px_rgba(82,107,72,.34)] border-[5px] border-[#FFFDF9]" aria-label={t('add')} data-testid="primary-capture-button"><Plus className="w-8 h-8"/></button><button type="button" onClick={()=>nav('today','today')} className={`${item} ${activeTab==='today'?'text-[#506B48]':'text-[#858078]'}`}><CalendarDays className="w-5 h-5"/><span>{t('today')}</span></button><button type="button" onClick={()=>setLanguageOpen(true)} aria-label={t('chooseLanguage')} className={`${item} text-[#858078]`}><Languages className="w-5 h-5"/><span>{copy.language}</span></button></div></nav><LanguagePicker open={languageOpen} onClose={()=>setLanguageOpen(false)} surface="bottom_nav"/></>; };
