export type MomentDetailCopy={categories:Record<string,string>;meal:string;close:string;location:string;rating:string;unspecified:string;body:string;hunger:string;fullness:string;energy:string;note:string;favorite:string;share:string;copied:string;copyFailed:string;edit:string;delete:string;deleteConfirm:(title:string)=>string;energyValues:Record<string,string>};

const COPY:Record<string,MomentDetailCopy>={
  en:{categories:{breakfast:'Breakfast',lunch:'Lunch',dinner:'Dinner',snack:'Snack',coffee:'Coffee',dessert:'Dessert'},meal:'Meal',close:'Close',location:'Location',rating:'Rating',unspecified:'Not specified',body:'Body signals',hunger:'Hunger before',fullness:'Fullness after',energy:'Energy after',note:'Note',favorite:'Favorite',share:'Share',copied:'Copied',copyFailed:'Copy failed',edit:'Edit',delete:'Delete',deleteConfirm:title=>`Delete “${title}”? This action cannot be undone.`,energyValues:{energized:'Energized',neutral:'Balanced',sluggish:'Sluggish',heavy:'Heavy'}},
  de:{categories:{breakfast:'Frühstück',lunch:'Mittagessen',dinner:'Abendessen',snack:'Snack',coffee:'Kaffee',dessert:'Dessert'},meal:'Mahlzeit',close:'Schließen',location:'Ort',rating:'Bewertung',unspecified:'Nicht angegeben',body:'Körpersignale',hunger:'Hunger vorher',fullness:'Sättigung danach',energy:'Energie danach',note:'Notiz',favorite:'Favorit',share:'Teilen',copied:'Kopiert',copyFailed:'Kopieren fehlgeschlagen',edit:'Bearbeiten',delete:'Löschen',deleteConfirm:title=>`„${title}“ löschen? Diese Aktion kann nicht rückgängig gemacht werden.`,energyValues:{energized:'Energiegeladen',neutral:'Ausgeglichen',sluggish:'Träge',heavy:'Schwer'}},
  fr:{categories:{breakfast:'Petit-déjeuner',lunch:'Déjeuner',dinner:'Dîner',snack:'Collation',coffee:'Café',dessert:'Dessert'},meal:'Repas',close:'Fermer',location:'Lieu',rating:'Évaluation',unspecified:'Non indiqué',body:'Signaux du corps',hunger:'Faim avant',fullness:'Satiété après',energy:'Énergie après',note:'Note',favorite:'Favori',share:'Partager',copied:'Copié',copyFailed:'Échec de la copie',edit:'Modifier',delete:'Supprimer',deleteConfirm:title=>`Supprimer « ${title} » ? Cette action est irréversible.`,energyValues:{energized:'Énergique',neutral:'Équilibré',sluggish:'Lent',heavy:'Lourd'}},
  ar:{categories:{breakfast:'الفطور',lunch:'الغداء',dinner:'العشاء',snack:'وجبة خفيفة',coffee:'قهوة',dessert:'حلويات'},meal:'وجبة',close:'إغلاق',location:'المكان',rating:'التقييم',unspecified:'غير محدد',body:'إشارات الجسم',hunger:'الجوع قبل الأكل',fullness:'الشبع بعد الأكل',energy:'الطاقة بعد الأكل',note:'ملاحظة',favorite:'مفضلة',share:'مشاركة',copied:'تم النسخ',copyFailed:'تعذر النسخ',edit:'تعديل',delete:'حذف',deleteConfirm:title=>`هل تريد حذف «${title}»؟ لا يمكن التراجع عن هذا الإجراء.`,energyValues:{energized:'نشيط',neutral:'متوازن',sluggish:'خامل',heavy:'ثقيل'}}
};

export const getMomentDetailCopy=(language:string):MomentDetailCopy=>COPY[language]||COPY.en;
