import React from 'react';
import { ArrowRight, Check, ChevronRight, Download, Plus, ShieldCheck, Sparkles, Sunrise, SunMedium, MoonStar } from 'lucide-react';
import { FoodMoment, DailyCheckIn, TimeOfDayPhase } from '../types';
import { analyzeNutritionType } from '../utils/nutritionTypeEngine';
import { getLocalDateKey } from '../utils/dateKey';
import { downloadCaryDataExport } from '../utils/dataExport';
import { getRecentTodayMoments } from '../utils/todayFeed';
interface Props { moments:FoodMoment[]; checkIns:DailyCheckIn[]; onOpenAddModal:()=>void; onOpenCheckInModal:()=>void; onSelectMoment:(m:FoodMoment)=>void; onNavigateToCoach:()=>void; onNavigateToTypeAnalysis:()=>void; onNavigateToTimeline:()=>void; onSaveCheckIn?:(c:Omit<DailyCheckIn,'id'|'createdAt'>)=>void; }
const demoC=(c:DailyCheckIn)=>/^checkin-\d{1,2}$/.test(c.id); const demoM=(m:FoodMoment)=>/^moment-\d{1,2}$/.test(m.id);
const meta:Record<TimeOfDayPhase,{label:string;sub:string;icon:React.ReactNode;bg:string}>={morning:{label:'Morgen',sub:'Schlaf & Frühstück',icon:<Sunrise className="w-5 h-5"/>,bg:'bg-[#F5A55B]'},midday:{label:'Mittag',sub:'Essen & Energie',icon:<SunMedium className="w-5 h-5"/>,bg:'bg-[#76A96A]'},evening:{label:'Abend',sub:'Essen & Rückblick',icon:<MoonStar className="w-5 h-5"/>,bg:'bg-[#76659A]'}};
const phase=(h:number):TimeOfDayPhase=>h<11?'morning':h<16?'midday':'evening';
export const TodayHomeView:React.FC<Props>=({moments,checkIns,onOpenAddModal,onOpenCheckInModal,onSelectMoment,onNavigateToCoach,onNavigateToTypeAnalysis,onNavigateToTimeline})=>{
 const key=getLocalDateKey(), now=phase(new Date().getHours()); const profile=React.useMemo(()=>analyzeNutritionType(moments,checkIns),[moments,checkIns]);
 const checks=checkIns.filter(c=>c.date===key&&!demoC(c)), meals=moments.filter(m=>m.date===key&&!demoM(m));
 const done={morning:checks.some(c=>c.timeOfDay==='morning')||meals.some(m=>m.category==='breakfast'),midday:checks.some(c=>c.timeOfDay==='midday')||meals.some(m=>m.category==='lunch'),evening:checks.some(c=>c.timeOfDay==='evening')||meals.some(m=>m.category==='dinner')};
 const eligible:TimeOfDayPhase[]=now==='morning'?['morning']:now==='midday'?['morning','midday']:['morning','midday','evening']; const next=eligible.find(p=>!done[p]); const target=next||now; const catchup=!!next&&next!==now;
 const recent=getRecentTodayMoments(meals,key,3); const heroImage=recent[0]?.imageUrl; const date=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
 const insight=profile.unlocked?profile.recommendedFocus:`Noch ${Math.max(0,profile.dataPointsNeeded-profile.dataPointsCurrent)} Einträge, dann kann Cary erste persönliche Zusammenhänge vorsichtig einordnen.`;
 return <div className="max-w-4xl mx-auto pb-4 animate-in fade-in duration-200">
  <section className="pt-3 sm:pt-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#A76042]">{date}</p><h1 className="mt-1 text-[42px] leading-none sm:text-6xl font-display font-black tracking-tight text-[#31221C]">Dein Tag.</h1><p className="mt-2 text-base text-[#76594B]">Cary verbindet, was du isst, wie du schläfst und wie du dich fühlst.</p></section>
  <section className="mt-6 relative min-h-[360px] sm:min-h-[410px] overflow-hidden rounded-[36px] bg-[#D96B43] shadow-[0_24px_60px_rgba(90,48,30,.22)]">{heroImage?<img src={heroImage} alt="" className="absolute inset-0 w-full h-full object-cover"/>:<div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,#F7B267_0,transparent_34%),radial-gradient(circle_at_20%_85%,#A8C686_0,transparent_38%),linear-gradient(135deg,#E9794D,#C95D43)]"/>}<div className="absolute inset-0 bg-gradient-to-t from-[#241712]/90 via-[#342018]/35 to-transparent"/><div className="relative min-h-[360px] sm:min-h-[410px] p-6 sm:p-9 flex flex-col justify-end text-white"><div className="absolute top-6 left-6 flex items-center gap-2 rounded-full bg-white/18 backdrop-blur-md px-3 py-2 text-xs font-bold">{meta[target].icon}{catchup?'Kurz nachholen':meta[target].label}</div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-white/75">Jetzt</p><h2 className="mt-2 max-w-lg text-3xl sm:text-4xl font-display font-black leading-tight">{next?(catchup?`${meta[target].label} fehlt noch.`:`Zeit für deinen ${meta[target].label.toLowerCase()}-Moment.`):'Für jetzt ist alles festgehalten.'}</h2><p className="mt-2 max-w-md text-sm sm:text-base text-white/80">{next?`${meta[target].sub}. Ein paar Sekunden reichen.`:'Genieß deinen Tag. Cary meldet sich, wenn der nächste Moment sinnvoll ist.'}</p><button onClick={next?onOpenCheckInModal:onOpenAddModal} className="mt-5 w-fit inline-flex items-center gap-2 rounded-full bg-[#FFF7ED] px-5 py-3.5 text-sm font-extrabold text-[#572F20] shadow-xl">{next?'Jetzt einchecken':'Etwas festhalten'}<ArrowRight className="w-4 h-4"/></button></div></section>
  <section className="mt-8"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#A76042]">Heute</p><h2 className="mt-1 text-2xl font-display font-black text-[#31221C]">Dein Rhythmus</h2></div><span className="text-xs font-bold text-[#8B6B5B]">{Object.values(done).filter(Boolean).length}/3</span></div><div className="mt-4 relative"><div className="absolute left-6 right-6 top-6 h-[3px] bg-[#E9D9CB] rounded-full"/><div className="relative grid grid-cols-3 gap-2">{(['morning','midday','evening'] as TimeOfDayPhase[]).map(p=>{const d=done[p], future=(p==='midday'&&now==='morning')||(p==='evening'&&now!=='evening');return <button key={p} disabled={future} onClick={d?onNavigateToTimeline:onOpenCheckInModal} className="text-center disabled:opacity-50"><span className={`relative mx-auto w-12 h-12 rounded-full flex items-center justify-center text-white shadow-md ${d?'bg-[#3F7954]':meta[p].bg}`}>{d?<Check className="w-5 h-5"/>:meta[p].icon}</span><strong className="block mt-2 text-sm text-[#3C2B24]">{meta[p].label}</strong><span className="block mt-0.5 text-[10px] text-[#907366]">{d?'erledigt':future?'später':'offen'}</span></button>})}</div></div></section>
  <section className="mt-9 grid sm:grid-cols-[1.15fr_.85fr] gap-4"><div className="rounded-[30px] bg-[#263C32] p-6 sm:p-7 text-white"><div className="flex items-center gap-2 text-[#CDE0C8]"><Sparkles className="w-5 h-5"/><span className="text-xs font-extrabold uppercase tracking-[.16em]">Cary entdeckt</span></div><h2 className="mt-4 text-2xl font-display font-black">Was hängt bei dir zusammen?</h2><p className="mt-2 text-sm leading-relaxed text-white/75">{insight}</p><button onClick={onNavigateToTypeAnalysis} className="mt-5 inline-flex items-center gap-1.5 font-bold text-sm text-[#E9F3E6]">Zusammenhänge entdecken <ChevronRight className="w-4 h-4"/></button></div><button onClick={onNavigateToCoach} className="rounded-[30px] bg-[#F1B35F] p-6 sm:p-7 text-left text-[#432B1D] flex flex-col justify-between min-h-52"><div><span className="text-xs font-extrabold uppercase tracking-[.16em]">Frag Cary</span><h2 className="mt-4 text-2xl font-display font-black">Was möchtest du über deinen Tag wissen?</h2></div><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Mit Cary sprechen <ArrowRight className="w-4 h-4"/></span></button></section>
  <section className="mt-9"><div className="flex items-center justify-between"><h2 className="text-2xl font-display font-black text-[#31221C]">Deine Momente</h2><button onClick={onNavigateToTimeline} className="text-xs font-bold text-[#A05E40]">Alle ansehen</button></div>{recent.length?<div className="mt-4 flex gap-3 overflow-x-auto pb-2 snap-x">{recent.map(m=><button key={m.id} onClick={()=>onSelectMoment(m)} className="relative shrink-0 w-[72%] sm:w-[31%] aspect-[4/5] rounded-[26px] overflow-hidden snap-start"><img src={m.imageUrl} alt="" className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent"/><div className="absolute bottom-0 p-4 text-left text-white"><p className="text-[10px] font-bold uppercase tracking-wide text-white/70">{m.label} · {m.time}</p><p className="mt-1 font-bold">{m.title}</p></div></button>)}</div>:<button onClick={onOpenAddModal} className="mt-4 w-full min-h-40 rounded-[28px] border-2 border-dashed border-[#E0CDBE] bg-[#FFF4E8] flex flex-col items-center justify-center text-[#87563F]"><Plus className="w-7 h-7"/><span className="mt-2 font-bold">Ersten Essensmoment festhalten</span></button>}</section>
  <details className="mt-8 text-xs text-[#8A7064]"><summary className="cursor-pointer flex items-center gap-2 font-bold"><ShieldCheck className="w-4 h-4"/>Daten & Transparenz</summary><div className="mt-3 pl-6"><p>Deine Tagebuchdaten bleiben in diesem Browser gespeichert. Für Cary-AI-Funktionen werden nur benötigte Inhalte übertragen.</p><button onClick={()=>downloadCaryDataExport(moments,checkIns)} className="mt-2 inline-flex items-center gap-2 font-bold"><Download className="w-4 h-4"/>Daten exportieren</button></div></details>
 </div>;
};