import type { AppLanguage } from '../i18n';
import type { MomentCategory } from '../types';

export const mealLabels: Record<AppLanguage, Record<MomentCategory, string>> = {
  en:{breakfast:'Breakfast',lunch:'Lunch',dinner:'Dinner',snack:'Snack',coffee:'Coffee',dessert:'Dessert',drinks:'Drinks',travel:'Travel'},
  ar:{breakfast:'الفطور',lunch:'الغداء',dinner:'العشاء',snack:'وجبة خفيفة',coffee:'قهوة',dessert:'حلويات',drinks:'مشروبات',travel:'سفر'},
  de:{breakfast:'Frühstück',lunch:'Mittagessen',dinner:'Abendessen',snack:'Snack',coffee:'Kaffee',dessert:'Dessert',drinks:'Getränke',travel:'Unterwegs'},
  fr:{breakfast:'Petit-déjeuner',lunch:'Déjeuner',dinner:'Dîner',snack:'En-cas',coffee:'Café',dessert:'Dessert',drinks:'Boissons',travel:'En déplacement'},
};

type Copy = {
  food:string; title:string; back:string; close:string; extraTitle:string; extraHelp:string; hideMain:string; anotherMeal:string;
  placeholder:string; confirm:string; addNote:string; optionalContext:string; saveChanges:string; saveMeal:string; defaultLocation:string; footer:string;
  voiceMessage:string; voiceFailed:string; voiceUnderstood:string; smartSuggestions:string; thinking:string; recognized:string; noMatch:string; remove:string;
  regionPriority:string; justType:string; picturesMatching:string; chooseByPicture:string; tapPicture:string; typeToNarrow:string; noPictures:string;
  photo:string; yourPhoto:string; analyzing:string; matchedDish:string; analyzingPhoto:string; addPhoto:string; noRandomPhoto:string;
  photoAnalyzingNote:string; photoSuggestion:string; photoLowConfidence:string; photoUnavailable:string;
  selected:(count:number)=>string;
};

export const mealEditorCopy: Record<AppLanguage, Copy> = {
  en:{
    food:'Food',title:'What did you have?',back:'Back',close:'Close',extraTitle:'Add an extra moment',extraHelp:'Breakfast, lunch and dinner belong to today’s check-ins. Use this for snacks, coffee, dessert or anything extra.',hideMain:'Hide main meals',anotherMeal:'Another unlogged meal?',placeholder:'Start typing… e.g. chicken pasta',confirm:'Confirm',addNote:'Add a note',optionalContext:'Optional context…',saveChanges:'Save changes',saveMeal:'Save meal',defaultLocation:'Not specified',footer:'Type a little — we’ll help with the rest.',
    voiceMessage:'Your voice message',voiceFailed:'We could not understand the message well enough to add foods automatically. Correct it or add items manually below.',voiceUnderstood:'We understood the message and added the recognized items below.',smartSuggestions:'Smart suggestions',thinking:'Thinking…',recognized:'Recognized',noMatch:'No match yet. You can confirm what you typed with ✓.',remove:'Remove',regionPriority:'We prioritize what fits your region',justType:'Just type — we’ll help complete it',picturesMatching:'Pictures matching what you typed',chooseByPicture:'Choose by picture',tapPicture:'Tap a picture to add it instantly',typeToNarrow:'Or start typing to narrow the choices',noPictures:'No matching pictures yet — use a smart suggestion or confirm what you typed.',photo:'Photo',yourPhoto:'Your photo',analyzing:'Analyzing',matchedDish:'Matched to dish',analyzingPhoto:'Analyzing…',addPhoto:'Add your photo',noRandomPhoto:'We won’t show a random photo that does not match your dish.',photoAnalyzingNote:'Analyzing the photo on your device…',photoSuggestion:'We found a suggestion — confirm it or correct it.',photoLowConfidence:'We were not confident enough. You can type the dish manually.',photoUnavailable:'Photo analysis is unavailable on this device. You can still save the photo and type manually.',selected:(count)=>`${count} dish${count===1?'':'es'} selected — add another if needed`,
  },
  ar:{
    food:'الطعام',title:'ماذا أكلت؟',back:'رجوع',close:'إغلاق',extraTitle:'أضف لحظة إضافية',extraHelp:'الفطور والغداء والعشاء تُسجّل من بطاقات اليوم. هنا للوجبات الخفيفة والقهوة والحلويات أو أي شيء إضافي.',hideMain:'إخفاء الوجبات الرئيسية',anotherMeal:'وجبة أخرى غير مسجلة؟',placeholder:'ابدأ بالكتابة… مثلاً طاجين',confirm:'تأكيد',addNote:'أضف ملاحظة',optionalContext:'معلومة إضافية اختيارية…',saveChanges:'حفظ التغييرات',saveMeal:'حفظ الوجبة',defaultLocation:'غير محدد',footer:'اكتب القليل فقط — سنساعدك في الباقي.',
    voiceMessage:'رسالتك الصوتية',voiceFailed:'لم نفهم الرسالة بما يكفي لإضافة أطعمة تلقائياً. صحّحها أو أضف العناصر يدوياً أدناه.',voiceUnderstood:'فهمنا الرسالة وأضفنا العناصر التي تعرّفنا عليها أدناه.',smartSuggestions:'اقتراحات ذكية',thinking:'يفكر…',recognized:'تم التعرف عليه',noMatch:'لم نجد تطابقاً. يمكنك تأكيد ما كتبته بعلامة ✓',remove:'حذف',regionPriority:'نقترح أولاً ما يناسب منطقتك',justType:'اكتب فقط، وسنكمل معك',picturesMatching:'صور تناسب ما كتبت',chooseByPicture:'اختر بالصورة',tapPicture:'اضغط على الصورة لإضافتها مباشرة',typeToNarrow:'أو ابدأ بالكتابة لتضييق الاختيارات',noPictures:'لا توجد صور مطابقة بعد — يمكنك استخدام الاقتراحات الذكية أو تأكيد ما كتبته.',photo:'الصورة',yourPhoto:'صورتك',analyzing:'جاري التحليل',matchedDish:'مطابقة للطبق',analyzingPhoto:'نحلل الصورة…',addPhoto:'أضف صورتك',noRandomPhoto:'لن نعرض صورة عشوائية لا تطابق طبقك.',photoAnalyzingNote:'نحلل الصورة على جهازك…',photoSuggestion:'وجدنا اقتراحاً — تأكد منه أو صححه.',photoLowConfidence:'لم نكن واثقين من الطبق. يمكنك كتابته يدوياً.',photoUnavailable:'تعذر تحليل الصورة على هذا الجهاز. ما زال بإمكانك حفظها والكتابة يدوياً.',selected:(count)=>`تم اختيار ${count} من أطباق هذه الوجبة — أضف طبقاً آخر إن وجد`,
  },
  de:{
    food:'Essen',title:'Was hast du gegessen?',back:'Zurück',close:'Schließen',extraTitle:'Zusätzlichen Moment hinzufügen',extraHelp:'Frühstück, Mittag- und Abendessen gehören zu den heutigen Check-ins. Hier kannst du Snacks, Kaffee, Dessert oder etwas Zusätzliches eintragen.',hideMain:'Hauptmahlzeiten ausblenden',anotherMeal:'Noch eine nicht erfasste Mahlzeit?',placeholder:'Tippe los… z. B. Hähnchenpasta',confirm:'Bestätigen',addNote:'Notiz hinzufügen',optionalContext:'Optionaler Hinweis…',saveChanges:'Änderungen speichern',saveMeal:'Mahlzeit speichern',defaultLocation:'Nicht angegeben',footer:'Ein paar Wörter genügen — wir helfen beim Rest.',
    voiceMessage:'Deine Sprachnachricht',voiceFailed:'Wir konnten die Nachricht nicht sicher genug verstehen, um Lebensmittel automatisch hinzuzufügen. Korrigiere sie oder füge die Einträge unten manuell hinzu.',voiceUnderstood:'Wir haben die Nachricht verstanden und die erkannten Einträge unten hinzugefügt.',smartSuggestions:'Intelligente Vorschläge',thinking:'Denkt nach…',recognized:'Erkannt',noMatch:'Noch kein Treffer. Bestätige deine Eingabe mit ✓.',remove:'Entfernen',regionPriority:'Wir bevorzugen Vorschläge, die zu deiner Region passen',justType:'Tippe einfach — wir helfen beim Vervollständigen',picturesMatching:'Bilder passend zu deiner Eingabe',chooseByPicture:'Nach Bild auswählen',tapPicture:'Tippe auf ein Bild, um es direkt hinzuzufügen',typeToNarrow:'Oder tippe, um die Auswahl einzugrenzen',noPictures:'Noch keine passenden Bilder — nutze einen intelligenten Vorschlag oder bestätige deine Eingabe.',photo:'Foto',yourPhoto:'Dein Foto',analyzing:'Analyse läuft',matchedDish:'Passend zum Gericht',analyzingPhoto:'Foto wird analysiert…',addPhoto:'Foto hinzufügen',noRandomPhoto:'Wir zeigen kein zufälliges Foto, das nicht zu deinem Gericht passt.',photoAnalyzingNote:'Das Foto wird auf deinem Gerät analysiert…',photoSuggestion:'Wir haben einen Vorschlag gefunden — bestätige oder korrigiere ihn.',photoLowConfidence:'Wir waren uns beim Gericht nicht sicher genug. Du kannst es manuell eingeben.',photoUnavailable:'Die Fotoanalyse ist auf diesem Gerät nicht verfügbar. Du kannst das Foto trotzdem speichern und das Gericht manuell eingeben.',selected:(count)=>`${count} Gericht${count===1?'':'e'} ausgewählt — füge bei Bedarf ein weiteres hinzu`,
  },
  fr:{
    food:'Repas',title:'Qu’as-tu mangé ?',back:'Retour',close:'Fermer',extraTitle:'Ajouter un moment supplémentaire',extraHelp:'Le petit-déjeuner, le déjeuner et le dîner se notent dans les check-ins du jour. Utilise cet écran pour un en-cas, un café, un dessert ou autre chose.',hideMain:'Masquer les repas principaux',anotherMeal:'Un autre repas non noté ?',placeholder:'Commence à écrire… ex. pâtes au poulet',confirm:'Confirmer',addNote:'Ajouter une note',optionalContext:'Contexte facultatif…',saveChanges:'Enregistrer les modifications',saveMeal:'Enregistrer le repas',defaultLocation:'Non précisé',footer:'Quelques mots suffisent — nous t’aidons pour le reste.',
    voiceMessage:'Ton message vocal',voiceFailed:'Nous n’avons pas compris le message avec assez de certitude pour ajouter automatiquement les aliments. Corrige-le ou ajoute les éléments manuellement ci-dessous.',voiceUnderstood:'Nous avons compris le message et ajouté ci-dessous les éléments reconnus.',smartSuggestions:'Suggestions intelligentes',thinking:'Réflexion…',recognized:'Reconnu',noMatch:'Aucune correspondance pour le moment. Confirme ta saisie avec ✓.',remove:'Supprimer',regionPriority:'Nous privilégions les suggestions adaptées à ta région',justType:'Écris simplement — nous t’aidons à compléter',picturesMatching:'Images correspondant à ta saisie',chooseByPicture:'Choisir par image',tapPicture:'Appuie sur une image pour l’ajouter directement',typeToNarrow:'Ou commence à écrire pour affiner les choix',noPictures:'Aucune image correspondante pour le moment — utilise une suggestion intelligente ou confirme ta saisie.',photo:'Photo',yourPhoto:'Ta photo',analyzing:'Analyse en cours',matchedDish:'Correspond au plat',analyzingPhoto:'Analyse de la photo…',addPhoto:'Ajouter une photo',noRandomPhoto:'Nous n’afficherons pas une image aléatoire qui ne correspond pas à ton plat.',photoAnalyzingNote:'Analyse de la photo sur ton appareil…',photoSuggestion:'Nous avons trouvé une suggestion — confirme-la ou corrige-la.',photoLowConfidence:'Nous n’étions pas assez certains du plat. Tu peux le saisir manuellement.',photoUnavailable:'L’analyse photo n’est pas disponible sur cet appareil. Tu peux tout de même enregistrer la photo et saisir le plat manuellement.',selected:(count)=>`${count} plat${count===1?'':'s'} sélectionné${count===1?'':'s'} — ajoute-en un autre si nécessaire`,
  },
};