import { DailyCheckIn, FoodMoment, FoodMood, MomentCategory, TimeOfDayPhase } from '../types';
import { VoiceCheckInResult, VoiceLanguage, VoiceMealEntry, VoiceWellbeingEntry } from '../apiClient';
import { getLocalDateKey } from './dateKey';

const mealCategories = new Set<MomentCategory>(['breakfast','lunch','dinner','snack','dessert','coffee','drinks']);
const phases = new Set<TimeOfDayPhase>(['morning','midday','evening']);

function validPhase(value: string): TimeOfDayPhase | null { return phases.has(value as TimeOfDayPhase) ? value as TimeOfDayPhase : null; }
function categoryFor(meal: VoiceMealEntry): MomentCategory { if(mealCategories.has(meal.category as MomentCategory))return meal.category as MomentCategory;if(meal.timeOfDay==='morning')return'breakfast';if(meal.timeOfDay==='midday')return'lunch';if(meal.timeOfDay==='evening')return'dinner';return'snack'; }
const primaryMealPatterns:Record<'breakfast'|'lunch'|'dinner',RegExp>={breakfast:/(?:\bbreakfast\b|\bfrühstück\b|الفطور|فطور|فطرت|اتفطرت)/i,lunch:/(?:\blunch\b|\bmittagessen\b|الغداء|غداء|الغدا|غدا|تغديت|اتغديت|غديت)/i,dinner:/(?:\bdinner\b|\babendessen\b|العشاء|عشاء|العشا|عشا|تعشيت|اتعشيت|عشيت)/i};
function explicitPrimaryCategory(transcript:string):MomentCategory|null{const text=transcript.toLocaleLowerCase();const found=(Object.entries(primaryMealPatterns) as Array<['breakfast'|'lunch'|'dinner',RegExp]>).filter(([,pattern])=>pattern.test(text)).map(([category])=>category);return found.length===1?found[0]:null}
function categoryForPhase(phase:TimeOfDayPhase):'breakfast'|'lunch'|'dinner'{return phase==='morning'?'breakfast':phase==='midday'?'lunch':'dinner'}
function explicitCategoryNearMeal(meal:VoiceMealEntry,transcript:string,phase:TimeOfDayPhase):MomentCategory|null{const text=transcript.toLocaleLowerCase();const candidates=[meal.mealTitle,...(meal.mealItems||[])].map(v=>v?.trim().toLocaleLowerCase()).filter((v):v is string=>Boolean(v)).sort((a,b)=>b.length-a.length);const mention=candidates.map(v=>({v,index:text.indexOf(v)})).filter(x=>x.index>=0).sort((a,b)=>a.index-b.index)[0];if(!mention)return null;const expected=categoryForPhase(phase);const regex=new RegExp(primaryMealPatterns[expected].source,'gi');let latest:RegExpExecArray|null=null;for(const match of text.matchAll(regex)){if((match.index??-1)<=mention.index)latest=match;else break}if(!latest)return null;const between=text.slice((latest.index??0)+latest[0].length,mention.index);if(/[.!؟]|(?:من بعد|بعدها|وبعدين|\bthen\b|\bafterwards\b|\bdanach\b|\bspäter\b)/i.test(between))return null;return expected}
function resolvedCategory(meal:VoiceMealEntry,transcript:string,singleMeal:boolean):MomentCategory{const category=categoryFor(meal);if(category!=='snack')return category;const phase=validPhase(meal.timeOfDay);if(phase){const nearby=explicitCategoryNearMeal(meal,transcript,phase);if(nearby)return nearby}if(singleMeal)return explicitPrimaryCategory(transcript)||category;return category}
function phaseForPrimaryMeal(meal: VoiceMealEntry, category: MomentCategory): TimeOfDayPhase | null { const explicit=validPhase(meal.timeOfDay);if(category==='breakfast')return explicit||'morning';if(category==='lunch')return explicit||'midday';if(category==='dinner')return explicit||'evening';return null; }
function normalizeMealIdentity(value:string){return value.trim().toLocaleLowerCase().replace(/[،,.;:!?؟]/g,' ').replace(/\s+/g,' ')}
function dedupeMeals(meals:VoiceMealEntry[]){const seen=new Set<string>();const unique:VoiceMealEntry[]=[];for(const meal of meals){if(!Array.isArray(meal.mealItems)||!meal.mealItems.length)continue;const title=meal.mealTitle||meal.mealItems.join(' · ');const items=meal.mealItems.map(normalizeMealIdentity).sort().join('|');const key=[categoryFor(meal),validPhase(meal.timeOfDay)||'',meal.time||'',normalizeMealIdentity(title),items].join('::');if(seen.has(key))continue;seen.add(key);unique.push(meal)}return unique}
function mergeMealTitle(existing:string|undefined,incoming:string){if(!existing)return incoming;const parts=existing.split(' · ').map(normalizeMealIdentity);return parts.includes(normalizeMealIdentity(incoming))?existing:`${existing} · ${incoming}`}
function foodMood(value:string):FoodMood|undefined{return['energized','satisfied','light','indulgent','comfort','joyful'].includes(value)?value as FoodMood:undefined}
function clampScore(value:number|undefined,max=5):number|undefined{const n=Number(value);if(!Number.isFinite(n)||n<=0)return undefined;return Math.max(1,Math.min(max,n))}
function labelFor(category:MomentCategory,language:VoiceLanguage){const ar:Record<string,string>={breakfast:'الفطور',lunch:'الغداء',dinner:'العشاء',snack:'وجبة خفيفة',dessert:'حلويات',coffee:'قهوة',drinks:'مشروب'};const en:Record<string,string>={breakfast:'Breakfast',lunch:'Lunch',dinner:'Dinner',snack:'Snack',dessert:'Dessert',coffee:'Coffee',drinks:'Drink'};const de:Record<string,string>={breakfast:'Frühstück',lunch:'Mittagessen',dinner:'Abendessen',snack:'Snack',dessert:'Dessert',coffee:'Kaffee',drinks:'Getränk'};return(language==='ar'?ar:language==='de'?de:en)[category]||category}

export function buildVoiceJournalEntries(result:VoiceCheckInResult,transcript:string,language:VoiceLanguage,now=new Date()):{moments:FoodMoment[];checkIns:DailyCheckIn[]}{
  const data=result.extractedData||{};const date=getLocalDateKey(now);const base=now.getTime();const rawMeals:VoiceMealEntry[]=Array.isArray(data.meals)&&data.meals.length?data.meals:(Array.isArray(data.mealItems)&&data.mealItems.length?[{category:data.mealCategory||'',timeOfDay:'',time:'',mealTitle:data.mealTitle||data.mealItems.join(' · '),mealItems:data.mealItems,hungerBefore:data.hungerBefore||0,fullnessAfter:data.fullnessAfter||0}]:[]);const meals=dedupeMeals(rawMeals);const categoryOf=(meal:VoiceMealEntry)=>resolvedCategory(meal,transcript,meals.length===1);
  const moments=meals.map((meal,index)=>{const category=categoryOf(meal);return{id:`voice-moment-${base}-${index}`,title:meal.mealTitle||meal.mealItems.join(' · '),label:labelFor(category,language),category,date,time:/^\d{2}:\d{2}$/.test(meal.time||'')?meal.time:'',location:language==='ar'?'غير محدد':language==='de'?'Nicht angegeben':'Not specified',locationCategory:'home' as const,imageUrl:'',rating:5,mood:'satisfied' as FoodMood,...(clampScore(meal.hungerBefore)?{hungerLevel:clampScore(meal.hungerBefore)}:{}),...(clampScore(meal.fullnessAfter)?{fullnessLevel:clampScore(meal.fullnessAfter)}:{}),coachFeedback:result.coachFeedback,notes:language==='ar'?'أضيفت من رسالة صوتية':language==='de'?'Aus einer Sprachnotiz hinzugefügt':'Added from a voice note',tags:['Voice',meal.timeOfDay||category],createdAt:base+index} satisfies FoodMoment});
  type PartialCheck={phase:TimeOfDayPhase;energyLevel?:number;mood?:FoodMood;stressLevel?:number;waterGlasses?:number;note?:string;sleep?:DailyCheckIn['sleep'];food?:DailyCheckIn['food'];time?:string};const grouped=new Map<TimeOfDayPhase,PartialCheck>();const ensure=(phase:TimeOfDayPhase)=>{if(!grouped.has(phase))grouped.set(phase,{phase});return grouped.get(phase)!};
  for(const meal of meals){const category=categoryOf(meal);const phase=phaseForPrimaryMeal(meal,category);if(!phase)continue;const target=ensure(phase);const hungerBefore=clampScore(meal.hungerBefore);const fullnessAfter=clampScore(meal.fullnessAfter);const mealTitle=meal.mealTitle||meal.mealItems.join(' · ');if(target.food){target.food={...target.food,mealTitle:mergeMealTitle(target.food.mealTitle,mealTitle),...(target.food.hungerBefore===undefined&&hungerBefore!==undefined?{hungerBefore}:{}),...(fullnessAfter!==undefined?{fullnessAfter}:{})}}else{target.food={mealTitle,category,...(hungerBefore!==undefined?{hungerBefore}:{}),...(fullnessAfter!==undefined?{fullnessAfter}:{})}}if(!target.time&&/^\d{2}:\d{2}$/.test(meal.time||''))target.time=meal.time}
  const wellbeing:VoiceWellbeingEntry[]=Array.isArray(data.wellbeingEntries)?data.wellbeingEntries:[];for(const entry of wellbeing){const phase=validPhase(entry.timeOfDay)||(now.getHours()<11?'morning':now.getHours()<16?'midday':'evening');const target=ensure(phase);const energy=clampScore(entry.energyLevel);const stress=clampScore(entry.stressLevel);const water=clampScore(entry.waterGlasses,30);if(energy!==undefined)target.energyLevel=energy;const mood=foodMood(entry.mood);if(mood)target.mood=mood;if(stress!==undefined)target.stressLevel=stress;if(water!==undefined)target.waterGlasses=water;if(entry.note)target.note=[target.note,entry.note].filter(Boolean).join(' · ')}
  const sleepHours=Number(data.sleepHours||0);const sleepQuality=clampScore(data.sleepQuality);const wake=['refreshed','normal','tired','exhausted'].includes(data.wakeFeeling||'')?data.wakeFeeling as NonNullable<DailyCheckIn['sleep']>['wakeFeeling']:undefined;if(sleepHours>0||sleepQuality||wake){const morning=ensure('morning');morning.sleep={...(sleepHours>0?{durationHours:Math.min(24,sleepHours)}:{}),...(sleepQuality?{quality:sleepQuality}:{}),...(wake?{wakeFeeling:wake}:{})}}
  const checkIns=Array.from(grouped.values()).map((entry,index)=>({id:`voice-checkin-${base}-${index}`,date,time:entry.time||'',timeOfDay:entry.phase,...(entry.sleep?{sleep:entry.sleep}:{}),...(entry.food?{food:entry.food}:{}),wellbeing:{...(entry.energyLevel!==undefined?{energyLevel:entry.energyLevel}:{}),...(entry.mood?{mood:entry.mood}:{}),...(entry.stressLevel!==undefined?{stressLevel:entry.stressLevel}:{}),...(entry.waterGlasses!==undefined?{waterGlasses:entry.waterGlasses}:{}),...(entry.note?{note:entry.note}:{}),voiceTranscription:transcript},coachSummary:language==='ar'?'استخرج تلقائياً من رسالتك الصوتية.':language==='de'?'Automatisch aus deiner Sprachnotiz erkannt.':'Automatically extracted from your voice note.',createdAt:base+100+index} satisfies DailyCheckIn));return{moments,checkIns};
}
